name: YouTube Video Processor

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube Video URL'
        required: true

jobs:
  process_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create videos directory
        run: mkdir -p videos

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install yt-dlp

      - name: Download YouTube Video (Using Cookies)
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > youtube_cookies.txt
          yt-dlp --cookies youtube_cookies.txt -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]" -o "videos/input.mp4" "${{ github.event.inputs.video_url }}"


      - name: Verify video download
        run: ls -l videos/ && test -f videos/input.mp4

      - name: Convert Video to MP4
        run: |
          ffmpeg -i "videos/input.mp4" -c:v libx264 -c:a aac -movflags +faststart "videos/output.mp4"

      - name: Upload Processed Video to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: "videos/output.mp4"
          tag_name: latest
          name: "Processed Video"
          body: "Here is your processed video."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}


      - name: Get Download Link
        run: |
          echo "Download your video from: https://github.com/${{ github.repository }}/releases/latest/download/output.mp4"
